(setq emacs-start-time (current-time))
(setq gc-cons-threshold most-positive-fixnum)
(add-hook 'after-init-hook #'(lambda ()
                               (setq gc-cons-threshold 5121024)))

(add-to-list 'load-path "~/.emacs.d/configs/")

(setq private/cache-directory "~/.emacs.d/.cache/")

(setq private/system-is-mac (eq system-type 'darwin))

(require 'init-package)
(require 'init-basic-settings)
(require 'init-evil)
(require 'init-support)
(require 'init-ui)
(require 'init-emacs)
(require 'init-chinese)
(require 'init-env)
(require 'init-elixir)
(require 'init-ivy)
(require 'init-magit)
(require 'init-projectile)
(require 'init-company)
(require 'init-spell-checking)
(require 'init-syntax-checking)
(require 'init-mac)
(require 'init-org)
(require 'init-file-nav)
(require 'init-jumping)
(require 'init-server)
(require 'init-sql)
(require 'init-dashboard)
