(setq emacs-start-time (current-time))
(setq gc-cons-threshold most-positive-fixnum)
(add-hook 'after-init-hook #'(lambda ()
                               (setq gc-cons-threshold 5121024)))

(setq private/config-directory "~/.emacs.d/")
(setq private/configs-directory "~/.emacs.d/configs/")

(setq comp-async-jobs-number 5
      comp-deferred-compilation t
      comp-async-report-warnings-errors nil)

(add-to-list 'load-path private/configs-directory)

(setq private/cache-directory "~/.emacs.d/.cache/")

(setq private/system-is-mac (eq system-type 'darwin))
(setq epg-pinentry-mode 'loopback)
(setq epa-pinentry-mode 'loopback)

(require 'init-package)
(require 'init-basic-settings)
(require 'init-prog)
(require 'init-evil)
(require 'init-support)
(require 'init-ui)
(require 'init-emacs)
(require 'init-chinese)
(require 'init-scheme)
(require 'init-elixir)
(require 'init-web)
(require 'init-ivy)
(require 'init-magit)
(require 'init-projectile)
(require 'init-company)
(require 'init-ansible)
(require 'init-spell-checking)
;; (require 'init-syntax-checking)
(require 'init-mac)
(require 'init-org)
(require 'init-file-nav)
(require 'init-jumping)
(require 'init-server)
(require 'init-sql)
(require 'init-lsp)
(require 'init-c)
(require 'init-r)
(require 'init-dashboard)
(put 'narrow-to-page 'disabled nil)
(put 'narrow-to-region 'disabled nil)
(put 'erase-buffer 'disabled nil)
